# Generated by Django 4.0.1 on 2022-01-27 01:55

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Categorria de eproductos ',
                'verbose_name_plural': 'Categorias de productos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Categorria de eproductos ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicator',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('descount_value', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical indicador de oferta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Unidad de medida',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nombre de producto')),
                ('description', models.CharField(max_length=200, verbose_name='description de producto')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='imagen de producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medidas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre de producto')),
                ('description', models.CharField(max_length=200, verbose_name='description de producto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen de producto')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('descount_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='indicador de ofertas')),
            ],
            options={
                'verbose_name': 'indicador de oferta',
                'verbose_name_plural': 'indicador de ofertas',
            },
        ),
    ]
