# Generated by Django 4.0.1 on 2022-02-07 03:48

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Model Base',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicator',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('descount_value', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical indicador de oferta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Unidad de medida',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medidas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre de producto')),
                ('description', models.CharField(max_length=200, verbose_name='description de producto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen de producto')),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct')),
                ('measure_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha de eliminacion')),
                ('descount_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='indicador de ofertas')),
            ],
            options={
                'verbose_name': 'indicador de oferta',
                'verbose_name_plural': 'indicador de ofertas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nombre de producto')),
                ('description', models.CharField(max_length=200, verbose_name='description de producto')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='imagen de producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct')),
            ],
            options={
                'verbose_name': 'historical Producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
