# Generated by Django 4.0.1 on 2022-02-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryproduct',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical category product'},
        ),
    ]
