# Generated by Django 4.0.1 on 2022-02-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
